name: check-abi
on:
  push:
    branches:
      - queue
      - abi
    paths:
      - '.github/workflows/abi.yaml'
      - '**.h'
      - '**.c'
  pull_request:
    branches:
      - master
      - queue
  workflow_dispatch:
env:
  ABI_BRANCH: ${{ secrets.ABI_BRANCH }}

jobs:
  save-and-test-ABI:
    runs-on: ubuntu-24.04
    steps:
      - name: set ABI branch
        if: ${{ env.ABI_BRANCH == '' }}
        run: echo "ABI_BRANCH=master" >> $GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v4
      - name: get reference ABI
        id: reference
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: abi.yaml
          branch: ${{ env.ABI_BRANCH }}
          name: abi
          path: reference-abi
      - name: update
        run: sudo apt-get update
      - name: dependencies
        run: >
          sudo apt-get install --yes gcc
          gcc make pkg-config abigail-tools
          libdevmapper-dev libreadline-dev libaio-dev libsystemd-dev
          libudev-dev libjson-c-dev liburcu-dev libcmocka-dev libedit-dev
          libmount-dev
      - name: create ABI
        run: make -Orecurse -j$(nproc) abi.tar.gz
      - name: save ABI
        uses: actions/upload-artifact@v4
        with:
          name: abi
          path: abi
          overwrite: true
      - name: compare ABI against reference
        id: compare
        continue-on-error: true
        if: ${{ steps.reference.outcome == 'success' }}
        run: make abi-test
      - name: save differences
        if: ${{ steps.compare.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: abi-test
          path: abi-test
          overwrite: true

      - name: fail
        # MUST use >- here, otherwise the condition always evaluates to true
        if: >-
          ${{
              env.ABI_BRANCH != github.ref_name &&
              (steps.reference.outcome == 'failure' ||
               steps.compare.outcome == 'failure')
          }}
        run: false
