name: compile and unit test on native arch
on:
  push:
    branches:
      - master
      - queue
      - tip
      - 'stable-*'
    paths:
      - '.github/workflows/native.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'
  pull_request:
    branches:
      - master
      - queue
      - 'stable-*'
    paths:
      - '.github/workflows/native.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'

jobs:
  stable:
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-jessie
          - debian-buster
          - debian-bullseye
          - debian-bookworm
          - debian-trixie
          - fedora-43
          - opensuse-leap-15.6
          - opensuse-leap-16.0
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: set archive name
        # Leap containers have cpio but not tar
        run: echo ARCHIVE_TGT=test-progs.cpio >> $GITHUB_ENV
        if: ${{ startswith(matrix.os, 'opensuse-leap-15') }}
      - name: set archive name
        run: echo ARCHIVE_TGT=test-progs.tar >> $GITHUB_ENV
        if: ${{ !startswith(matrix.os, 'opensuse-leap-15') }}

      - name: build and test
        id: test
        if: ${{ matrix.os != 'debian-jessie' }}
        uses: mosteo-actions/docker-run@v1
        with:
          image: ghcr.io/mwilck/multipath-build-${{ matrix.os }}
          command: -j -Orecurse test
        continue-on-error: true

      - name: build and test (jessie)
        id: test_jessie
        # On jessie, we use libreadline 5 (no licensing issue)
        if: ${{ matrix.os == 'debian-jessie' }}
        uses: mosteo-actions/docker-run@v1
        with:
          image: ghcr.io/mwilck/multipath-build-${{ matrix.os }}
          command: -j -Orecurse READLINE=libreadline test
        continue-on-error: true

      - name: create ${{ env.ARCHIVE_TGT }}
        if: ${{ matrix.os != 'debian-jessie' }}
        uses: mosteo-actions/docker-run@v1
        with:
          image: ghcr.io/mwilck/multipath-build-${{ matrix.os }}
          command: ${{ env.ARCHIVE_TGT }}
      - name: create ${{ env.ARCHIVE_TGT }} (jessie)
        if: ${{ matrix.os == 'debian-jessie' }}
        uses: mosteo-actions/docker-run@v1
        with:
          image: ghcr.io/mwilck/multipath-build-${{ matrix.os }}
          command: READLINE=libreadline ${{ env.ARCHIVE_TGT }}

      - name: upload binary archive
        uses: actions/upload-artifact@v4
        with:
          name: native-${{ matrix.os }}-${{ matrix.variant.arch }}
          path: ${{ env.ARCHIVE_TGT }}
          overwrite: true

      - name: fail
        run: /bin/false
        if: >-
          ${{ ( matrix.os == 'debian-jessie' &&
                steps.test_jessie.outcome != 'success' ) ||
              ( matrix.os != 'debian-jessie' &&
                steps.test.outcome != 'success' ) }}
  clang:
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-buster
          - debian-bullseye
          - debian-bookworm
          - debian-trixie
          - fedora-43
          - opensuse-leap-15.6
          - opensuse-leap-16.0
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
        include:
          - os: debian-jessie
            variant:
              arch: x86_64
              runner: ubuntu-24.04
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: set archive name
        # Leap containers have cpio but not tar
        run: echo ARCHIVE_TGT=test-progs.cpio >> $GITHUB_ENV
        if: ${{ startswith(matrix.os, 'opensuse-leap-15') }}
      - name: set archive name
        run: echo ARCHIVE_TGT=test-progs.tar >> $GITHUB_ENV
        if: ${{ !startswith(matrix.os, 'opensuse-leap-15') }}

      - name: clang
        id: test
        if: ${{ matrix.os != 'debian-jessie' }}
        uses: mosteo-actions/docker-run@v1
        with:
          image: ghcr.io/mwilck/multipath-build-${{ matrix.os }}
          params: -e CC=clang
          command: -j -Orecurse test
        continue-on-error: true
      - name: clang (jessie)
        id: test_jessie
        if: ${{ matrix.os == 'debian-jessie' }}
        uses: mosteo-actions/docker-run@v1
        with:
          image: ghcr.io/mwilck/multipath-build-${{ matrix.os }}
          params: -e CC=clang
          command: -j -Orecurse READLINE=libreadline test
        continue-on-error: true

      - name: create ${{ env.ARCHIVE_TGT }}
        if: ${{ matrix.os != 'debian-jessie' }}
        uses: mosteo-actions/docker-run@v1
        with:
          image: ghcr.io/mwilck/multipath-build-${{ matrix.os }}
          command: ${{ env.ARCHIVE_TGT }}
        if: >-
          ${{ ( matrix.os == 'debian-jessie' &&
                steps.test_jessie.outcome != 'success' ) ||
              ( matrix.os != 'debian-jessie' &&
                steps.test.outcome != 'success' ) }}
      - name: create ${{ env.ARCHIVE_TGT }} (jessie)
        if: ${{ matrix.os == 'debian-jessie' }}
        uses: mosteo-actions/docker-run@v1
        with:
          image: ghcr.io/mwilck/multipath-build-${{ matrix.os }}
          command: READLINE=libreadline ${{ env.ARCHIVE_TGT }}
        if: >-
          ${{ ( matrix.os == 'debian-jessie' &&
                steps.test_jessie.outcome != 'success' ) ||
              ( matrix.os != 'debian-jessie' &&
                steps.test.outcome != 'success' ) }}

      - name: upload binary archive
        uses: actions/upload-artifact@v4
        with:
          name: clang-${{ matrix.os }}-${{ matrix.variant.arch }}
          path: ${{ env.ARCHIVE_TGT }}
          overwrite: true
        if: >-
          ${{ ( matrix.os == 'debian-jessie' &&
                steps.test_jessie.outcome != 'success' ) ||
              ( matrix.os != 'debian-jessie' &&
                steps.test.outcome != 'success' ) }}

      - name: fail
        run: /bin/false
        if: >-
          ${{ ( matrix.os == 'debian-jessie' &&
                steps.test_jessie.outcome != 'success' ) ||
              ( matrix.os != 'debian-jessie' &&
                steps.test.outcome != 'success' ) }}

  root-test:
    needs: stable
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-jessie
          - debian-buster
          - debian-bullseye
          - debian-bookworm
          - debian-trixie
          - fedora-43
          - opensuse-leap-15.6
          - opensuse-leap-16.0
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    steps:
      - name: mpath
        run: sudo modprobe dm_multipath
      - name: brd
        run: sudo modprobe brd rd_nr=1 rd_size=65536

      - name: checkout
        uses: actions/checkout@v1

      - name: download binary archive
        uses: actions/download-artifact@v4
        with:
          name: native-${{ matrix.os }}-${{ matrix.variant.arch }}
      - name: unpack binary archive
        run: cpio -idv < test-progs.cpio
        if: ${{ startswith(matrix.os, 'opensuse-leap-15') }}
      - name: unpack binary archive
        run: tar xfmv test-progs.tar
        if: ${{ !startswith(matrix.os, 'opensuse-leap-15') }}

      - name: run root tests
        uses: mosteo-actions/docker-run@v1
        with:
          image: ghcr.io/mwilck/multipath-build-${{ matrix.os }}
          guest-dir: /__w/multipath-tools/multipath-tools
          host-dir: ${{ github.workspace }}
          params: >
            --workdir /__w/multipath-tools/multipath-tools --privileged
            -v /dev/ram0:/dev/ram0 -e DIO_TEST_DEV=/dev/ram0
          command: -C tests directio.out dmevents.out
        id: root-test
        continue-on-error: true
      - name: show root test output
        run: for o in tests/*.out; do echo "===== $o ====="; cat "$o"; done
      - name: fail
        run: /bin/false
        if: ${{ steps.root-test.outcome == 'failure' }}
