name: compile and unit test on native arch
on:
  push:
    branches:
      - master
      - queue
      - tip
    paths:
      - '.github/workflows/native.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'
  pull_request:
    branches:
      - master
      - queue
    paths:
      - '.github/workflows/native.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'

jobs:
  stable:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-jessie
          - debian-buster
          - debian-bullseye
          - debian-bookworm
          - fedora-40
          - opensuse-leap
    container: ghcr.io/mwilck/multipath-build-${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build and test
        if: ${{ matrix.os != 'debian-jessie' }}
        run: make -j -Orecurse test
      - name: build and test (jessie)
        # On jessie, we use libreadline 5 (no licensing issue)
        if: ${{ matrix.os == 'debian-jessie' }}
        run: make -j -Orecurse READLINE=libreadline test

      - name: clean
        run: make clean
      - name: clang
        if: ${{ matrix.os != 'debian-jessie' }}
        env:
          CC: clang
        run: make -j -Orecurse test
      - name: clang (jessie)
        if: ${{ matrix.os == 'debian-jessie' }}
        env:
          CC: clang
        run: make READLINE=libreadline test
