name: compile and unit test on rolling distros
on:
  push:
    branches:
      - master
      - queue
      - tip
      - 'stable-*'
    paths:
      - '.github/workflows/rolling.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'
  pull_request:
    branches:
      - master
      - queue
      - 'stable-*'
    paths:
      - '.github/workflows/rolling.yaml'
      - '**.h'
      - '**.c'
      - '**Makefile*'
      - '**.mk'
  # run weekly to catch rolling distro changes
  schedule:
    - cron: '30 06 * * 1'

jobs:
  rolling:
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian-sid
          - opensuse-tumbleweed
          - fedora-rawhide
        variant:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
        include:
          - os: alpine
            variant:
              arch: x86_64
              runner: ubuntu-24.04
    runs-on: ${{ matrix.variant.runner }}
    container: ghcr.io/mwilck/multipath-build-${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build and test
        run: make READLINE=libreadline -j -Orecurse test
      - name: clean
        run: make -j -Orecurse clean
      - name: clang
        env:
          CC: clang
        run: make READLINE=libedit -j -Orecurse test
